package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"encoder/application/producer"
	"encoder/graph/model"
)

// IncludeJobQueue is the resolver for the includeJobQueue field.
func (r *mutationResolver) IncludeJobQueue(ctx context.Context, input model.JobQueue) (*model.JobQueueResponse, error) {
	pr := producer.NewAccountProducer()
	return pr.Produce(input)
}

// Account is the resolver for the Account field.
func (r *queryResolver) Account(ctx context.Context) ([]*model.Account, error) {
	return r.AcccountService.FindAvailableAccounts()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
