// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: proto/account_loan.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountServiceRequestClient is the client API for AccountServiceRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceRequestClient interface {
	CreateAccounts(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	CreateAccountsStream(ctx context.Context, opts ...grpc.CallOption) (AccountServiceRequest_CreateAccountsStreamClient, error)
	CreateAccountsStreamBidirecional(ctx context.Context, opts ...grpc.CallOption) (AccountServiceRequest_CreateAccountsStreamBidirecionalClient, error)
	FindAccounts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FindAccountsResponse, error)
}

type accountServiceRequestClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceRequestClient(cc grpc.ClientConnInterface) AccountServiceRequestClient {
	return &accountServiceRequestClient{cc}
}

func (c *accountServiceRequestClient) CreateAccounts(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/grpc.AccountServiceRequest/CreateAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceRequestClient) CreateAccountsStream(ctx context.Context, opts ...grpc.CallOption) (AccountServiceRequest_CreateAccountsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AccountServiceRequest_ServiceDesc.Streams[0], "/grpc.AccountServiceRequest/CreateAccountsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountServiceRequestCreateAccountsStreamClient{stream}
	return x, nil
}

type AccountServiceRequest_CreateAccountsStreamClient interface {
	Send(*CreateRequest) error
	CloseAndRecv() (*CreateResponseList, error)
	grpc.ClientStream
}

type accountServiceRequestCreateAccountsStreamClient struct {
	grpc.ClientStream
}

func (x *accountServiceRequestCreateAccountsStreamClient) Send(m *CreateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *accountServiceRequestCreateAccountsStreamClient) CloseAndRecv() (*CreateResponseList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CreateResponseList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *accountServiceRequestClient) CreateAccountsStreamBidirecional(ctx context.Context, opts ...grpc.CallOption) (AccountServiceRequest_CreateAccountsStreamBidirecionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &AccountServiceRequest_ServiceDesc.Streams[1], "/grpc.AccountServiceRequest/CreateAccountsStreamBidirecional", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountServiceRequestCreateAccountsStreamBidirecionalClient{stream}
	return x, nil
}

type AccountServiceRequest_CreateAccountsStreamBidirecionalClient interface {
	Send(*CreateRequest) error
	Recv() (*CreateResponse, error)
	grpc.ClientStream
}

type accountServiceRequestCreateAccountsStreamBidirecionalClient struct {
	grpc.ClientStream
}

func (x *accountServiceRequestCreateAccountsStreamBidirecionalClient) Send(m *CreateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *accountServiceRequestCreateAccountsStreamBidirecionalClient) Recv() (*CreateResponse, error) {
	m := new(CreateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *accountServiceRequestClient) FindAccounts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FindAccountsResponse, error) {
	out := new(FindAccountsResponse)
	err := c.cc.Invoke(ctx, "/grpc.AccountServiceRequest/FindAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceRequestServer is the server API for AccountServiceRequest service.
// All implementations must embed UnimplementedAccountServiceRequestServer
// for forward compatibility
type AccountServiceRequestServer interface {
	CreateAccounts(context.Context, *CreateRequest) (*CreateResponse, error)
	CreateAccountsStream(AccountServiceRequest_CreateAccountsStreamServer) error
	CreateAccountsStreamBidirecional(AccountServiceRequest_CreateAccountsStreamBidirecionalServer) error
	FindAccounts(context.Context, *Empty) (*FindAccountsResponse, error)
	mustEmbedUnimplementedAccountServiceRequestServer()
}

// UnimplementedAccountServiceRequestServer must be embedded to have forward compatible implementations.
type UnimplementedAccountServiceRequestServer struct {
}

func (UnimplementedAccountServiceRequestServer) CreateAccounts(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccounts not implemented")
}
func (UnimplementedAccountServiceRequestServer) CreateAccountsStream(AccountServiceRequest_CreateAccountsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateAccountsStream not implemented")
}
func (UnimplementedAccountServiceRequestServer) CreateAccountsStreamBidirecional(AccountServiceRequest_CreateAccountsStreamBidirecionalServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateAccountsStreamBidirecional not implemented")
}
func (UnimplementedAccountServiceRequestServer) FindAccounts(context.Context, *Empty) (*FindAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAccounts not implemented")
}
func (UnimplementedAccountServiceRequestServer) mustEmbedUnimplementedAccountServiceRequestServer() {}

// UnsafeAccountServiceRequestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceRequestServer will
// result in compilation errors.
type UnsafeAccountServiceRequestServer interface {
	mustEmbedUnimplementedAccountServiceRequestServer()
}

func RegisterAccountServiceRequestServer(s grpc.ServiceRegistrar, srv AccountServiceRequestServer) {
	s.RegisterService(&AccountServiceRequest_ServiceDesc, srv)
}

func _AccountServiceRequest_CreateAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceRequestServer).CreateAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AccountServiceRequest/CreateAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceRequestServer).CreateAccounts(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountServiceRequest_CreateAccountsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountServiceRequestServer).CreateAccountsStream(&accountServiceRequestCreateAccountsStreamServer{stream})
}

type AccountServiceRequest_CreateAccountsStreamServer interface {
	SendAndClose(*CreateResponseList) error
	Recv() (*CreateRequest, error)
	grpc.ServerStream
}

type accountServiceRequestCreateAccountsStreamServer struct {
	grpc.ServerStream
}

func (x *accountServiceRequestCreateAccountsStreamServer) SendAndClose(m *CreateResponseList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *accountServiceRequestCreateAccountsStreamServer) Recv() (*CreateRequest, error) {
	m := new(CreateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AccountServiceRequest_CreateAccountsStreamBidirecional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountServiceRequestServer).CreateAccountsStreamBidirecional(&accountServiceRequestCreateAccountsStreamBidirecionalServer{stream})
}

type AccountServiceRequest_CreateAccountsStreamBidirecionalServer interface {
	Send(*CreateResponse) error
	Recv() (*CreateRequest, error)
	grpc.ServerStream
}

type accountServiceRequestCreateAccountsStreamBidirecionalServer struct {
	grpc.ServerStream
}

func (x *accountServiceRequestCreateAccountsStreamBidirecionalServer) Send(m *CreateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *accountServiceRequestCreateAccountsStreamBidirecionalServer) Recv() (*CreateRequest, error) {
	m := new(CreateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AccountServiceRequest_FindAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceRequestServer).FindAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AccountServiceRequest/FindAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceRequestServer).FindAccounts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountServiceRequest_ServiceDesc is the grpc.ServiceDesc for AccountServiceRequest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountServiceRequest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.AccountServiceRequest",
	HandlerType: (*AccountServiceRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccounts",
			Handler:    _AccountServiceRequest_CreateAccounts_Handler,
		},
		{
			MethodName: "FindAccounts",
			Handler:    _AccountServiceRequest_FindAccounts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateAccountsStream",
			Handler:       _AccountServiceRequest_CreateAccountsStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateAccountsStreamBidirecional",
			Handler:       _AccountServiceRequest_CreateAccountsStreamBidirecional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/account_loan.proto",
}
