// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	AccountNumber string      `json:"accountNumber"`
	AccountType   string      `json:"accountType"`
	CustomerName  string      `json:"customerName"`
	LoanProducts  []*Products `json:"loanProducts"`
}

type JobQueue struct {
	TypeAccount int      `json:"typeAccount"`
	Quantity    int      `json:"quantity"`
	Products    []string `json:"products"`
}

type JobQueueResponse struct {
	IsStarted *bool `json:"isStarted,omitempty"`
}

type Mutation struct {
}

type Products struct {
	ID                 string  `json:"id"`
	LoanType           string  `json:"loanType"`
	NumberInstallments int     `json:"numberInstallments"`
	ValueInstallments  float64 `json:"valueInstallments"`
	TotalInstalments   float64 `json:"totalInstalments"`
}

type Query struct {
}
