// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	AccountNumber string      `json:"accountNumber"`
	AccountType   string      `json:"accountType"`
	CustomerName  string      `json:"customerName"`
	LoanProducts  []*Products `json:"loanProducts"`
}

type Products struct {
	ID                 string  `json:"id"`
	LoanType           string  `json:"loanType"`
	NumberInstallments int     `json:"numberInstallments"`
	ValueInstallments  float64 `json:"valueInstallments"`
	TotalInstalments   float64 `json:"totalInstalments"`
}

type Query struct {
}
